spring.datasource.url =jdbc:sqlserver://localhost:1433;databaseName=sistemaPedidos;encrypt=true;trustServerCertificate=true;
spring.datasource.username = sa
spring.datasource.password = Seba39035169
spring.datasource.driverClassName = com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA specific configs
spring.jpa.database-platform =  org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto = update
spring.main.allow-bean-definition-overriding=true

logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibernate.type = TRACE


spring.main.allow-circular-references = true